import "./globals.css";
import { Roboto } from "next/font/google";
import NavigationBar from "../components/header/NavigationBar";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        <NavigationBar />
        {children}
      </body>
    </html>
  );
}
